### ISSUE TITLE
Should cmd "credo ..." be cmd "mix credo ..." ?

### ISSUE THREAD

**Issue by potterdai** [mintcore/SublimeLinter-contrib-credo#1]
Really appreciate this plugin.

Just got one question:
Following credo installation instruction: https://github.com/rrrene/credo#using-credo-as-stand-alone
It seems the credo will not be added to the path, however "mix credo" will definitely work.

Should cmd "credo ..." be cmd "mix credo ..." in this case?

**Comment by nhooyr** [comment]
Changing it makes the plugin work for me.

**Comment by johantell** [comment]
Sorry for the late response... For some reason github decided not to notify me on events in this repo

**Comment by johantell** [comment]
And thanks for pointing out the error :)
